In [1]:
import numpy as np
import pandas as pd
import recsys as rs
import SLIM_BPR_PY as SLIMBPR

In [2]:
dataset = pd.read_csv('Data/train_final.csv','\t')
tr_info = pd.read_csv('Data/tracks_final.csv','\t')

In [3]:
IX_items, _, IX_tgt_playlists, _ = rs.create_sparse_indexes(tracks_info=tr_info, playlists=dataset)

In [4]:
URM = rs.create_tgt_URM(IX_tgt_playlists, IX_items, dataset)
URM = URM.tocsr()

Calculated 0 users ratings over 45649
Calculated 1000 users ratings over 45649
Calculated 2000 users ratings over 45649
Calculated 3000 users ratings over 45649
Calculated 4000 users ratings over 45649
Calculated 5000 users ratings over 45649
Calculated 6000 users ratings over 45649
Calculated 7000 users ratings over 45649
Calculated 8000 users ratings over 45649
Calculated 9000 users ratings over 45649
Calculated 10000 users ratings over 45649
Calculated 11000 users ratings over 45649
Calculated 12000 users ratings over 45649
Calculated 13000 users ratings over 45649
Calculated 14000 users ratings over 45649
Calculated 15000 users ratings over 45649
Calculated 16000 users ratings over 45649
Calculated 17000 users ratings over 45649
Calculated 18000 users ratings over 45649
Calculated 19000 users ratings over 45649
Calculated 20000 users ratings over 45649
Calculated 21000 users ratings over 45649
Calculated 22000 users ratings over 45649
Calculated 23000 users ratings over 45649
Calculated 24000 users ratings over 45649
Calculated 25000 users ratings over 45649
Calculated 26000 users ratings over 45649
Calculated 27000 users ratings over 45649
Calculated 28000 users ratings over 45649
Calculated 29000 users ratings over 45649
Calculated 30000 users ratings over 45649
Calculated 31000 users ratings over 45649
Calculated 32000 users ratings over 45649
Calculated 33000 users ratings over 45649
Calculated 34000 users ratings over 45649
Calculated 35000 users ratings over 45649
Calculated 36000 users ratings over 45649
Calculated 37000 users ratings over 45649
Calculated 38000 users ratings over 45649
Calculated 39000 users ratings over 45649
Calculated 40000 users ratings over 45649
Calculated 41000 users ratings over 45649
Calculated 42000 users ratings over 45649
Calculated 43000 users ratings over 45649
Calculated 44000 users ratings over 45649
Calculated 45000 users ratings over 45649

In [ ]:
recommender = SLIMBPR.SLIM_BPR_Python(URM)
recommender.fit(topK=20)

In [60]:
recommendetions = np.array([])
for p in IX_tgt_playlists.values:
            avg_sims = URM[p,:].dot(recommender.S).toarray().ravel()
            top = rs.top5_outside_playlist(avg_sims, p, train, IX_tgt_playlists, IX_tgt_items)
            recommendetions = np.append(recommendetions, rs.sub_format(top))
            if (p % 1000 == 0):
                print('Recommended ' + str(p) + ' users over ' + str(IX_tgt_playlists.values.shape[0]))
print(recommendetions.shape[0])
print(tgt_playlists['playlist_id'].shape[0])
print(IX_tgt_playlists.shape[0])
recs = pd.DataFrame({'playlist_id' : IX_tgt_playlists.index.values, 'track_ids' : recommendetions})
recs

Recommended 0 users over 84
84
84
84

    playlist_id                                track_ids
0       7670304     424298 2720582 1647509 335496 209196
1       7559928  1914337 2637110 1639389 3006129 1088475
2       7623847  1374934 1916878 3186602 2448296 2249460
3      11490052            3825653 3554491 375801 661804
4         44442  3338219 2053418 3309392 2859364 2053293
5       5896390     375801 1914337 504848 245412 2859364
6       7751126     3554491 375801 392524 859666 2491432
7       4916097   3872735 354409 2448296 2225942 2053293
8      11266592  2077566 3727132 1137264 2752338 2378652
9       3510855          2225942 3846669 2053293 1858575
10      3167809     2969100 1137407 415827 42623 2367877
11      3841665            168894 2491432 2859364 661804
12      7656514   209196 1210836 1797879 1858575 1647509
13     11400914   545960 1088475 3006129 1675189 2637110
14      6364732                            375801 661804
15      7069134          1730098 2720582 2509644 2788426
16     10831627     330927 2243161 2800858 2969100 42623
17        61413    731135 3033496 3263385 2800858 324994
18      8709232   3822505 3603719 2214856 2772683 731135
19      7452956          2720582 2445373 1647509 1295096
20      3611013   392524 2378652 1994478 1088475 1885521
21      6132763  2959004 1587557 3532480 1374934 3590649
22      3091337    162450 1088475 2637110 143798 2370906
23      6571192       110375 3263385 375801 661804 88403
24      5778535   2204983 487970 1588326 2491432 2359404
25      8258539    2788426 2509644 961859 335496 1295096
26     10757724            3411503 15136 2788426 2509644
27      2899769   3846669 2839253 573534 4474831 2388710
28      7039000   3554491 2881150 2370906 661804 2053293
29      8503661   1675189 3550491 168894 2882283 2053418
..          ...                                      ...
54     10729751   2619282 377148 3532600 1707628 2684386
55     10178398            330927 2243161 517373 3103440
56      5080355  1351381 3462720 2208924 3091415 2454612
57     10999059    377148 2619282 2454612 926181 1707628
58      5950577                   4474831 1707628 906707
59      7397758     377148 2619282 961859 245412 1188811
60      3053437     961859 287886 3351099 926181 2378652
61      7541410     2367877 883490 110375 661804 2208924
62      4150008  2800858 2543050 2684386 1185658 1181241
63     10212684  2800319 1295096 2720582 2788426 1730098
64       261823     1053213 15136 2454612 3554491 926181
65      3874112   573534 2053293 1351381 2388710 3846669
66      6159690    961859 717926 1707628 3532600 1647509
67     10759325   335496 3498040 1858575 2720582 1181241
68      8357862                                   661804
69      4443682   2720582 560910 2800319 1647509 3411311
70      3700731   1916878 2455640 686797 3851156 2765601
71      5850400                     2651693 22480 134408
72       814547             377148 133630 209344 2873439
73      6571398             160338 2359404 904737 134408
74      6834071      2243161 330927 42623 1510424 731135
75     10142322     3554491 1155078 375801 1204180 15136
76      5782816   1137407 415827 2788426 1730098 3411311
77      3573226    883490 961859 3137064 1647509 2752338
78      4349961           3550491 3261289 661804 2509644
79     11525473           162658 1445410 2543050 2800858
80      7075085      160338 2651693 904737 2359404 22480
81      4906906          3872735 2053293 2249460 2859364
82      5446100                  2249460 1053213 2720582
83      1064306    2895585 222438 330892 3003315 1941088

[84 rows x 2 columns]

In [64]:
map_eval = rs.evaluate(recs, test, 'MAP')
map_eval

Calculated AP for playlist #0

0.08765873015873016